services:
  initdb:
    build:
      context: ./base
      dockerfile: Dockerfile
    volumes:
      - db_data:/data
    environment:
      - HELPDESK_DB_PATH=/data/helpdesk.db
    command: python init_db.py --reset --seed
    # Este servicio inicializa la base de datos antes de que el backend la use

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - db_data:/data
    ports:
      - "8000:8000"
    environment:
      - HELPDESK_DB_PATH=/data/helpdesk.db
    depends_on:
      - initdb
    # El backend espera que la base esté lista, por eso depende de initdb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_BACKEND_URL=http://localhost:8000
    # El frontend se conecta al backend en el puerto 8000

volumes:
  db_data:
    # Volumen compartido entre initdb y backend para la base de datos
