version: "3.8"

services:
  initdb:
    build:
      context: ./base
      dockerfile: Dockerfile
    volumes:
      - db_data:/data
    command: python init_db.py --reset --seed

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - db_data:/data
    ports:
      - "8000:8000"
    environment:
      - HELPDESK_DB_PATH=/data/helpdesk.db
    depends_on:
      - initdb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_BACKEND_URL=http://localhost:8000

volumes:
  db_data:
