[tool.black]
line-length = 88
target-version = ['py310']

[tool.isort]
profile = "black"

[tool.ruff]
line-length = 88

[tool.ruff.lint]
extend-ignore = ["E203"]
select = ["E", "F", "W", "C90", "TC"]

[tool.pytest]
addopts = "-q"
